<a href="https://colab.research.google.com/github/leo-cuvelier/DATA-IA-PROJECT/blob/L%C3%A9o/Datascience_et_IA_projet_Leo_Cuvelier_Simon_Dos_Anjos_Adrien_Estardy_groupe_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Imports**

In [ ]:
import pandas as pd

**Dataset**

In [ ]:
df = pd.read_csv("/content/sample_data/full_data.csv")

**Clean**

In [ ]:


#Combien de valeurs manquantes
df.isnull().sum()
df = df.drop(df.columns[14:],axis=1)
df = df.drop(columns=['Année','Observation Value','Observation Status'])
df.isnull().sum()

STRUCTURE         0
STRUCTURE_ID      0
STRUCTURE_NAME    0
ACTION            0
COU               0
Pays              0
SER               0
Série             0
TIME_PERIOD       0
OBS_VALUE         0
OBS_STATUS        0
dtype: int64

**Clean verifications**

5 first values

In [ ]:
df.head(10)

,STRUCTURE,STRUCTURE_ID,STRUCTURE_NAME,ACTION,COU,Pays,SER,Série,TIME_PERIOD,OBS_VALUE,OBS_STATUS
0,DATAFLOW,OECD:DF_TEL(1.0),Statistiques sur les télécommunications,I,AUS,Australie,TEL-ACC-LINE,Total des lignes d'accès téléphoniques,2015,8.490000e+06,A
1,DATAFLOW,OECD:DF_TEL(1.0),Statistiques sur les télécommunications,I,AUS,Australie,TEL-ACC-PATH,Total des voies d'accès de communication,2015,4.141300e+07,A
2,DATAFLOW,OECD:DF_TEL(1.0),Statistiques sur les télécommunications,I,AUS,Australie,TEL-MOB-SUB,Total des abonnements au téléphone cellulaire ...,2015,2.616000e+07,A
3,DATAFLOW,OECD:DF_TEL(1.0),Statistiques sur les télécommunications,I,AUS,Australie,TEL-MOB-PP,Abonnements au téléphone cellulaire mobile uti...,2015,9.255000e+06,A
4,DATAFLOW,OECD:DF_TEL(1.0),Statistiques sur les télécommunications,I,AUS,Australie,TEL-REV-TOT,Total des recettes des télécommunications,2015,4.191950e+10,A
5,DATAFLOW,OECD:DF_TEL(1.0),Statistiques sur les télécommunications,I,AUS,Australie,TEL-REV-USD,Total des recettes des télécommunications USD,2015,3.151842e+10,A
6,DATAFLOW,OECD:DF_TEL(1.0),Statistiques sur les télécommunications,I,AUS,Australie,TEL-INV-TOT,Investissements totaux dans les télécommunicat...,2015,8.044289e+09,A
7,DATAFLOW,OECD:DF_TEL(1.0),Statistiques sur les télécommunications,I,AUS,Australie,TEL-INV-USD,Investissements totaux dans les télécommunicat...,2015,6.048338e+09,A
8,DATAFLOW,OECD:DF_TEL(1.0),Statistiques sur les télécommunications,I,AUT,Autriche,TEL-ACC-LINE,Total des lignes d'accès téléphoniques,2015,2.505857e+06,A
9,DATAFLOW,OECD:DF_TEL(1.0),Statistiques sur les télécommunications,I,AUT,Autriche,TEL-ACC-PATH,Total des voies d'accès de communication,2015,1.843238e+07,A

Values

In [ ]:
df.describe()

       TIME_PERIOD     OBS_VALUE
count  2113.000000  2.113000e+03
mean   2015.990535  2.340311e+11
std       1.410494  2.913215e+12
min    2014.000000  0.000000e+00
25%    2015.000000  4.796070e+05
50%    2016.000000  1.512367e+07
75%    2017.000000  1.244447e+09
max    2018.000000  5.786433e+13

TIME_PERIOD column

In [ ]:
print(df['TIME_PERIOD'])

0       2015
1       2015
2       2015
3       2015
4       2015
        ...
2108    2018
2109    2018
2110    2018
2111    2018
2112    2018
Name: TIME_PERIOD, Length: 2113, dtype: int64

Dataframe trié par séries

In [ ]:
série = df.sort_values('Série')
print(set(df['Série'].values))

{'Total des recettes des télécommunications', 'Abonnements au téléphone cellulaire mobile utilisant des cartes prépayés', 'Nombre d’abonnés à la télévision par câble', "Total des lignes d'accès téléphoniques", "Total des voies d'accès de communication", 'Investissements totaux dans les télécommunications (pour lignes fixes et réseau mobile cellulaire) USD', 'Total des abonnements au téléphone cellulaire mobile pour 100 habitants', 'Total Internet Protocol (IP) telephone subscriptions', "Total des voies d'accès de communication pour 100 habitants", 'Total des recettes des télécommunications USD', 'Total des abonnements au téléphone cellulaire mobile', 'Investissements totaux dans les télécommunications (pour lignes fixes et réseau mobile cellulaire)'}

Investissement total dans les télécommunications (fixes, cellulaires, mobiles et autres services sans fil) USD

In [ ]:
investmentTotalInTelecomunications = df[df['Série'] == 'Investissements totaux dans les télécommunications (pour lignes fixes et réseau mobile cellulaire)']
investmentTotalInTelecomunications.head()
investmentTotalInTelecomunications['OBS_VALUE'].describe()

count    1.690000e+02
mean     2.463187e+11
std      1.024478e+12
min      6.713288e+07
25%      6.156217e+08
50%      5.340280e+09
75%      1.091497e+10
max      6.758800e+12
Name: OBS_VALUE, dtype: float64

Total des abonnements au téléphone cellulaire mobile

In [ ]:
TotalSubscriptionCellular = df[df['Série'] =='Total des abonnements au téléphone cellulaire mobile']
TotalSubscriptionCellular.head()
TotalSubscriptionCellular['OBS_VALUE'].describe()

count    1.890000e+02
mean     8.683066e+07
std      2.668681e+08
min      3.700470e+05
25%      6.985035e+06
50%      1.535355e+07
75%      6.365869e+07
max      1.742751e+09
Name: OBS_VALUE, dtype: float64

Line/Column

In [ ]:
print('nombre de lignes: ', df.shape[0],'\nnombre de colonnes: ',df.shape[1])
print(type(df['Série']))
print("test")

nombre de lignes:  2113
nombre de colonnes:  11
<class 'pandas.core.series.Series'>